name: Playwright Tests
run-name: Playwright Tests - ${{ github.ref_name }}
on:
  push:
    branches: [ main, start-pages ]
  pull_request:
    branches: [ main, setup ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      WEBQUOTE_BASE_URL: https://www-acc.santam.co.za/webquotepl/
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm test
    - name: Upload Playwright debug artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-debug-artifacts
        path: |
          playwright-report/
          test-results/
        retention-days: 30
